'use strict';
const fs = require('fs');
const C = require('./lc-chess.js');
const D = JSON.parse(fs.readFileSync(__dirname + '/lc-data.json', 'utf8'));

function tokToMove(st, tok) {
  const t = String(tok).replace(/[!?]+$/, '');
  if (/^[a-h][1-8][a-h][1-8][qrbnQRBN]?$/.test(t)) {
    const from = C.nameSq(t.slice(0,2)), to = C.nameSq(t.slice(2));
    const promo = t.length === 5 ? ({q:C.PT.QUEEN,r:C.PT.ROOK,b:C.PT.BISHOP,n:C.PT.KNIGHT})[t[4].toLowerCase()] : undefined;
    const legal = C.allLegal(st, st.turn).filter(m => m.from === from && m.to === to && (!promo || m.promo === promo));
    return legal[0] || null;
  }
  const m = C.parseSAN(st, t);
  return (m && !m.ambiguous) ? m : null;
}
function seq(fen, moves) {
  let st = C.parseFEN(fen || 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1');
  const out = [];
  for (const tok of String(moves).split(/\s+/).filter(Boolean)) {
    const m = tokToMove(st, tok);
    if (!m) return { ok: false, pairs: out, badToken: tok };
    out.push([m.from, m.to]);
    st = C.doMove(st, m);
  }
  return { ok: true, pairs: out };
}

const payload = { traps: [], acadTraps: [], openings: [], routes: [], puzzles: [] };

D.TRAPS.forEach(t => { const r = seq(null, t.moves); payload.traps.push({ name: t.name, pairs: r.pairs, badToken: r.badToken || null }); });
(D.ACADEMY.traps || []).forEach(t => { const r = seq(null, t.moves); payload.acadTraps.push({ name: t.name, pairs: r.pairs, badToken: r.badToken || null }); });
(D.ACADEMY.openings || []).forEach(o => { const r = seq(null, o.moves); payload.openings.push({ name: o.name, pairs: r.pairs, badToken: r.badToken || null }); });
(D.ROUTES || []).forEach(b => b.lines.forEach(l => {
  const cleaned = l.moves.replace(/\d+\.(\.\.)?/g, ' ').replace(/[!?]+/g, ' ').trim();
  const r = seq(null, cleaned); payload.routes.push({ name: b.branch + ' / ' + l.name, pairs: r.pairs, badToken: r.badToken || null });
}));

D.PUZZLES.forEach((p, i) => {
  const st = C.parseFEN(p.fen);
  const entry = { i, name: p.desc, fen: p.fen, solution: p.solution, board: st.board, turn: st.turn, ep: st.ep,
                  cr: st.castling, legalCount: C.allLegal(st, st.turn).length, mateIn1: [], solutionPair: null, claimsMate1: (p.type === 'mate1' || /mate in 1/i.test(p.desc)) };
  for (const m of C.allLegal(st, st.turn)) {
    const after = C.doMove(st, m);
    if (C.inCheckmate(after, after.turn)) entry.mateIn1.push([m.from, m.to, m.promo || 0]);
  }
  const sm = tokToMove(st, p.solution);
  if (sm) entry.solutionPair = [sm.from, sm.to, sm.promo || 0];
  payload.puzzles.push(entry);
});

fs.writeFileSync(__dirname + '/../shots/lcpayload.json', JSON.stringify(payload));

const probeJs = `// lcprobe.js (generated by _loop/research/lc-mkprobe.js) - drives the REAL page engine
(function () {
  var P = __PAYLOAD__;
  var R = { stage: 'start' };
  function pub() { window.__PROBE = JSON.stringify(R); }
  function sqOf(p) { return p; }
  function loadFrame(cb) {
    var f = document.createElement('iframe');
    f.style.cssText = 'position:fixed;left:0;top:0;width:390px;height:844px;border:0;z-index:99999';
    f.src = '/games/chess.html';
    f.onload = function () { setTimeout(function () { cb(f); }, 700); };
    document.body.appendChild(f);
  }
  loadFrame(function (f) {
    var w = f.contentWindow;
    try {
      R.hasChessMods = !!w.ChessMods;
      if (!w.ChessMods) { R.stage = 'no-chessmods'; pub(); return; }
      w.ChessMods.api.setBot(false);

      R.trapCheck = w.__trapCheck();

      function playSeq(list, out) {
        for (var i = 0; i < list.length; i++) {
          var e = list[i], bad = -1;
          w.resetGame(); w.ChessMods.api.setBot(false);
          for (var j = 0; j < e.pairs.length; j++) {
            if (!w.ChessMods.api.playMove(e.pairs[j][0], e.pairs[j][1])) { bad = j; break; }
          }
          out.push({ name: e.name, plies: e.pairs.length, failedAt: bad, nodeBadToken: e.badToken,
                     over: w.ChessMods.api.isOver(), result: w.eval('game.result') });
        }
      }
      R.acadTraps = []; playSeq(P.acadTraps, R.acadTraps);
      R.stage = 'acadTraps'; pub();
      R.openings = []; playSeq(P.openings, R.openings);
      R.stage = 'openings'; pub();
      R.routes = []; playSeq(P.routes, R.routes);
      R.stage = 'routes'; pub();

      R.puzzles = [];
      for (var k = 0; k < P.puzzles.length; k++) {
        var pz = P.puzzles[k];
        w.loadPuzzle(k);
        var st = JSON.parse(w.eval('JSON.stringify({turn:game.turn,ep:game.epTarget,cr:game.castlingRights,over:game.gameOver})'));
        var board = Array.prototype.slice.call(w.ChessMods.api.board);
        var same = JSON.stringify(board) === JSON.stringify(pz.board);
        var legal = w.getAllLegalMoves(board, pz.turn, pz.ep, pz.cr);
        var mates = [];
        for (var q = 0; q < legal.length; q++) {
          var m = legal[q];
          var res = w.makeMove(board, m, { castlingRights: pz.cr });
          var replies = w.getAllLegalMoves(res.board, 1 - pz.turn, res.ep, res.castling);
          if (replies.length === 0 && w.isInCheck(res.board, 1 - pz.turn)) mates.push([m.from, m.to, m.promo || 0]);
        }
        var played = null, over = null, result = null;
        if (pz.solutionPair) {
          played = w.ChessMods.api.playMove(pz.solutionPair[0], pz.solutionPair[1]);
          over = w.ChessMods.api.isOver();
          result = w.eval('game.result');
        }
        R.puzzles.push({ i: k, desc: (pz.name || '').slice(0, 46), boardMatchesNode: same, turn: st.turn, epMatches: JSON.stringify(st.ep) === JSON.stringify(pz.ep),
                         legalPage: legal.length, legalNode: pz.legalCount, matesPage: mates.length, matesNode: pz.mateIn1.length,
                         solPlayed: played, over: over, result: result, claimsMate1: pz.claimsMate1 });
        R.stage = 'puzzle-' + k; pub();
      }
      R.stage = 'done'; pub();
    } catch (e) { R.error = String(e && e.stack || e); R.stage = 'exception'; pub(); }
  });
})();
`;
const withPayload = probeJs.replace('__PAYLOAD__', JSON.stringify(payload));
fs.writeFileSync(__dirname + '/../shots/lcprobe.js', withPayload);
fs.writeFileSync(__dirname + '/../shots/lcprobe.html', ['<!DOCTYPE html>','<html><head><meta charset="utf-8"><title>lc learning-content probe</title></head>','<body style="margin:0;background:#111"><script src="lcprobe.js"></script></body></html>',''].join(String.fromCharCode(10)));
console.log('wrote _loop/shots/lcprobe.js (' + withPayload.length + ' bytes) and lcprobe.html');
console.log('payload sizes: traps=' + payload.traps.length + ' acadTraps=' + payload.acadTraps.length + ' openings=' + payload.openings.length + ' routes=' + payload.routes.length + ' puzzles=' + payload.puzzles.length);
console.log('puzzles with 0 mate-in-1 per Node: ' + payload.puzzles.filter(p => p.mateIn1.length === 0).map(p => p.i).join(',') || 'none');
console.log('puzzle legal counts: ' + payload.puzzles.map(p => p.i + ':' + p.legalCount).join(' '));
